### PR TITLE
handle errors for unknown instruction and cannot open file and malloc…

### LINKED ISSUE #18: show errors
If, for any reason, it’s not possible to open the file, print the error message Error: Can't open file <file>, followed by a new line, and exit with the status EXIT_FAILURE

If the file contains an invalid instruction, print the error message L<line_number>: unknown instruction <opcode>, followed by a new line, and exit with the status EXIT_FAILURE
where is the line number where the instruction appears.
Line numbers always start at 1

If you can’t malloc anymore, print the error message Error: malloc failed, followed by a new line, and exit with status EXIT_FAILURE.

### PR DESCRIPTION
**Pull request by arleybri18**
… error
fixes #18

### CODE REVIEW

File: build_instruction.c [hunk 1]
```diff
@@ -13,14 +14,21 @@ void build_instruction(stack_t **head, unsigned int line_number)
 
 	/*iterate over array to split the opcode and data*/
 	line = strtok(linevalue, " ");
+	printf("la linea es %s\n", line);
```
Comment (Fermec28) [inline build_instruction.c]: delete this line

**Review by Fermec28 — COMMENTED** [review]
its ok
